services:
  fiap-x-worker:
    image: fiapx/api:latest
    build:
      context: ..
      args:
        target: 'fiap-x-worker'
    restart: 'on-failure'
    environment:
      NODE_ENV: 'development'
      APP_NAME: 'FiapXWorker'
      APP_DESCRIPTION: 'Worker Component for Fiap X'
      APP_VERSION: '1.0.0'
      PORT: '3000'
      LOG_LEVEL: 'debug'
      LOG_FORMAT: 'pretty' # pretty | json
      TRAFFIC_INSPECTION_HTTP: 'all' # inbound|outbound|all|none
      TRAFFIC_INSPECTION_AMQP: 'all' # inbound|outbound|all|none
      ROUTE_PREFIX: ''
      AMQP_URL: 'amqp://fiapx:fiapx@rabbitmq:5672'
      AWS_ACCESS_KEY_ID: 'test'
      AWS_SECRET_ACCESS_KEY: 'test'
      AWS_SESSION_TOKEN: ''
      AWS_REGION: 'us-east-1'
      AWS_S3_BUCKET_NAME: 'fiap7soat-f5-hacka-tests'
      AWS_S3_LOCALSTACK_ENDPOINT: 'http://aws_s3:4566'
      AWS_S3_USE_LOCALSTACK: 'true'
    command: sh -c "sleep 10 && npm run start:prod"
    ports:
      - 4000:3000
    depends_on: [aws_s3, rabbitmq]
  aws_s3:
    image: localstack/localstack:s3-latest
    ports:
      - 4566:4566
    volumes:
      - ./init-s3.py:/etc/localstack/init/ready.d/init-s3.py
  rabbitmq:
    image: fiapx/rabbitmq:3-management-delayed
    build:
      context: .
      dockerfile: ./Dockerfile.rabbitmq
    # hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'fiapx'
      RABBITMQ_DEFAULT_PASS: 'fiapx'
    ports:
      - 5672:5672
      - 15672:15672
