services:
  aws_s3:
    image: localstack/localstack:s3-latest
    container_name: fiap-x-aws-s3
    ports:
      - 4566:4566
    volumes:
      - ./localstack/init-s3.py:/etc/localstack/init/ready.d/init-s3.py
  rabbitmq:
    image: fiapx/rabbitmq:3-management-delayed
    build:
      context: ./localstack
      dockerfile: ./Dockerfile.rabbitmq
    container_name: fiap-x-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'fiapx'
      RABBITMQ_DEFAULT_PASS: 'fiapx'
    ports:
      - 5672:5672
      - 15672:15672
