---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-x-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-x-worker
  template:
    metadata:
      labels:
        app: fiap-x-worker
    spec:
      terminationGracePeriodSeconds: 90
      automountServiceAccountToken: false
      containers:
        - name: fiap-x-worker-app
          image: gm50x/fiap-x-worker:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fiap-x-worker
          env:
            - name: NODE_ENV
              value: "production"
            - name: APP_NAME
              value: "FiapXWorker"
            - name: APP_DESCRIPTION
              value: "Worker Component for Fiap X"
            - name: APP_VERSION
              value: "1.0.0"
            - name: PORT
              value: "3000"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "pretty" # pretty | json
            - name: TRAFFIC_INSPECTION_HTTP
              value: "all" # inbound|outbound|all|none
            - name: TRAFFIC_INSPECTION_AMQP
              value: "all" # inbound|outbound|all|none
            - name: ROUTE_PREFIX
              value: "dev/fiap-x-worker"
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 20m
              memory: "128Mi"
            limits:
              cpu: 150m
              memory: "256Mi"
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 15
            httpGet:
              path: /dev/fiap-x-worker/healthz
              port: 3000
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /dev/fiap-x-worker/healthz/self
              port: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-x-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-x-worker
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 150
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-x-worker-lb-srv
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: fiap-x-worker
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
